*** Settings ***
Documentation     The localization texts for Main Page are stored here


*** Variable ***
&{MAIN_PAGE_TEXT}
...			title=User Information
...			key_column_title=key
...         value_column_title=value
...         username_key=Username
...         username_value=%s
...         first_name_key=First name
...         first_name_value=%s
...         last_name_key=Last name
...         last_name_value=%s
...         phone_number_key=Phone number
...         phone_number_value=%s