*** Settings ***
Documentation     The localization texts for Registration Page are stored here


*** Variable ***
&{REGISTRATION_PAGE_TEXT}
...			form_title=Register
...			username_label=Username
...			password_label=Password
...         firstname_label=First name
...         lastname_label=Family Name
...         phone_number_label=Phone number
...         register_button_text=Register
...         already_registered_error=User %s is already registered.


